#!/usr/bin/env python3
"""Concatenate firmware modules into firmware/standalone.py for uflash.

uflash embeds exactly one script into the MicroPython hex, so the three
firmware modules are merged. Cross-module imports are stripped; the
microbit/random imports are hoisted to the top once.
"""

import ast
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FW = ROOT / "firmware"

PARTS = [FW / "Cutebot.py", FW / "autonomous.py", FW / "main.py"]

STRIP_PREFIXES = (
    "from microbit import",
    "from Cutebot import",
    "from autonomous import",
    "import random",
    "import radio",
)


def docstring_lines(text: str) -> set[int]:
    """Line numbers (1-based) occupied by docstrings, found via the AST."""
    lines: set[int] = set()
    tree = ast.parse(text)
    for node in ast.walk(tree):
        if isinstance(node, (ast.Module, ast.ClassDef, ast.FunctionDef)):
            body = node.body
            if body and isinstance(body[0], ast.Expr) \
                    and isinstance(body[0].value, ast.Constant) \
                    and isinstance(body[0].value.value, str):
                lines.update(range(body[0].lineno, body[0].end_lineno + 1))
    return lines


def minify(text: str) -> str:
    """Drop cross-module imports, comments, blank lines and docstrings.

    uflash caps the embedded script at ~20KB, so the generated file trades
    readability for size; the real sources in firmware/ stay documented."""
    doc = docstring_lines(text)
    kept = []
    for n, line in enumerate(text.splitlines(), 1):
        s = line.strip()
        if not s or s.startswith("#") or n in doc:
            continue
        if s.startswith(STRIP_PREFIXES):
            continue
        kept.append(line)
    return "\n".join(kept)


def main() -> None:
    chunks = [
        "# Auto-generated by scripts/build_standalone.py - do not edit.\n",
        "from microbit import *\n",
        "import random\n",
        "import radio\n",
    ]
    for path in PARTS:
        chunks.append(minify(path.read_text()))
        chunks.append("\n")

    out = FW / "standalone.py"
    out.write_text("".join(chunks))
    print(f"Wrote {out} ({out.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
